### ISSUE TITLE
Something about the root URL is very confusing/distracting to me

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#25]
As a user, the fancy footwork where the input to the "root URL" box gets added on to wherever the page is being hosting is creating some confusion for me. I can't quite see clearly what it is that is throwing me off, but perhaps we can talk about it soon to figure it out together.

When I first saw the page, the fact that one of the first things you notice is that you can seeming only link to root urls that are hosted on bio.dredge.edu is confusing. 

![screen shot 2019-03-05 at 11 47 59 am](https://user-images.githubusercontent.com/7449762/53821856-93b1c700-3f3c-11e9-9084-a3d19e59dc86.png)

I understand that you have to download it first and then all those text boxes become useful, but maybe there's some visual way to heighten the fact that even though they have access to those text boxes, they should not start using them until they are looking at a local version of the page.

OR - Is there a way to make those text boxes only visible if you are looking at the file that is downloaded to your own computer? And then once it gets uploaded to your webserver or whatever, the version that other people have will, once again, not have the text boxes?

**Comment by ptgolden** [comment]
> you can seeming only link to root urls that are hosted on bio.dredge.edu is confusing.
Not the case-- you could enter in, for example, `http://example.com/blahblah/worms`. However, everything will be resolved *relative* to the current URL. I intend to add a section to the documentation about the general structure of how data is loaded. It's very important that everything is a URL, and everything is downloaded relative to a certain location. That should help some of the (understandable) confusion about being presented with a "root URL" immediately. (And again, if #28 is the case, some of this will change).


> Is there a way to make those text boxes only visible if you are looking at the file that is downloaded to your own computer

There are a couple issues with this, but they are both reasonably handled. You're right, the "Create new project" function should not be always presented to someone, since it should be relatively rare.

1. Unfortunately, there is no foolproof way to tell if someone is running a server locally. The best that could be done is to assume that a locally-served webpage is at one of the following URLs: <http://localhost>, <http://127.0.0.1>, <http://0.0.0.0>. That should handle 90% of cases, which is probably good enough.

2. I don't want to totally disable the editing form on non-local servers. It should still be possible for someone configuring a new site to, for example, debug issues that show up on the server by changing values. But it would be possible to only have the option of showing the form by adding something to the URL, like <http://dredge.bio.unc.edu/?page=home&project=worms&debug=true>



This depends on what we decide to do in #28, but one solution might be this: Instead of having a `projects.json` file that includes a list of projects, a DrEdGE installation either **has** a project configured along with it, or **does not** have one. If it does not have one, it prompts a person to configure a dataset. This would happen if they downloaded the application and served it locally. (By default, there would not be a dataset configured). If it did have a dataset, the parameters could be adjusted by adding `&debug=true` to the URL.

Does that sound OK to you? I think it's a pretty elegant solution.

**Comment by tintori** [comment]
Ooh, yea, that sounds very nice to me.
