### ISSUE TITLE
Two places where the user is prompted to name the project

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#26]
When my new project shows up in the datasets menu, it is named as I named it on the configuration page, not as I named it in the "projects.json" file. Does the name in the json file have consequence anywhere?

Just curious. I instinctively gave it an uglier, more utilitarian name on the configuration page and a more presentable name in the json file, fwiw.

**Comment by ptgolden** [comment]
Uglier, more utilitarian is the right way to go. It's used internally for keeping track of different projects, and in the URL to represent a selected project. (e.g. http://dredge.bio.unc.edu/?page=home&project=worms). "worms" is the uglier name that is used in http://dredge.bio.unc.edu/projects.json

If #28 is the case, and there will only ever be one project, this key would not be necessary. I'm going to close this, and we can talk about it more in that issue, because I'm convinced that one-project-per-website is the way to go.
