### ISSUE TITLE
naming convensions

### ISSUE THREAD

**Issue by tintori** [ptgolden/dredge#3]
- everywhere we use "RPKM" (table, heatmap, etc) we should use "abundance" instead.

- everywhere we use "gene" we should use "transcript" instead.

- in the MA plot "Average Transcript Level" should be "Average Transcript Abundance"

- in table "logCPM" should be "logATA" to match the axis of the MA plot.

**Comment by ptgolden** [comment]
I edited your comment to format this as a list rather than a block of code. In Markdown, if you put four+ spaces or a tab before some text, it means "the following is source code. Do not break lines, and make it look like it's a listing of source code."

Compare:

	- it's hard being a man living in a garbage pail it's hard being a man living in a garbage pail it's hard being a man living in a garbage pail it's hard being a man living in a garbage pail

vs

- it's hard being a man living in a garbage pail it's hard being a man living in a garbage pail it's hard being a man living in a garbage pail it's hard being a man living in a garbage pail

The difference between those is that the top one has a tab preceding it

**Comment by tintori** [comment]
Yep, this is a universal change, not just for labels. Looks like you already went ahead and made those changes in the code as well, great.
Now I have a question: The changes you're making, should I be able to see the updates at dredge.ptgolden.org? Because I'm still seeing "RPKM" and "logCPM" over there.

**Comment by ptgolden** [comment]
No, I haven't uploaded anything yet. They'll be on dredge.bio.unc.edu

**Comment by ptgolden** [comment]
Also, can you tell me-- 

> Do transcripts represent a gene? Can this kind of data represent anything other than a gene?

I'm just trying to get a grasp on things before I change terminology throughout the code

**Comment by tintori** [comment]
Oh right, sorry to leave that hanging.

Yes, transcripts represent genes. The gene is the segment of DNA, and the transcripts are the RNA copies that are made from that DNA (sometimes lots of copies, sometimes few, sometimes none at all). So "genes" are never discussed quantitatively (because there are always just two copies, sitting in the genome), and "transcripts" are the units whose abundance we care about.

**Comment by ptgolden** [comment]
"Gene" renamed to "Transcript" everywhere in f0025ac5092c1bf7b7f2ee65625861d5a2ca683d
